// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig, env } from "prisma/config"

const appEnv = env("APP_ENV")

export default defineConfig({
  schema: "prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: appEnv === "production" ? env("DATABASE_URL") : env("LOCAL_DATABASE_URL"),
  },
})
